from typing import Any, Literal

from pydantic import BaseModel, Field


class TaskData(BaseModel):
    name: str | None = Field(default=None, description="Name of the task.", examples=["Check input safety"])
    run_id: str = Field(
        default="",
        description="ID of the task run to pair state updates to.",
        examples=["847c6285-8fc9-4560-a83f-4e6285809254"],
    )
    state: Literal["new", "running", "complete"] | None = Field(
        default=None,
        description="Current state of given task instance.",
        examples=["running"],
    )
    result: Literal["success", "error"] | None = Field(
        default=None,
        description="Result of given task instance.",
        examples=["success", "error"],
    )
    data: dict[str, Any] = Field(default_factory=dict, description="Additional data generated by the task.")

    def completed(self) -> bool:
        return self.state == "complete"

    def completed_with_error(self) -> bool:
        return self.completed() and self.result == "error"


class TaskDataStatus:
    def __init__(self):
        import streamlit as st

        self.status = st.status("running")
        self.current_task_data: dict[str, TaskData] = {}

    def add_and_draw_task_data(self, task_data: TaskData) -> None:
        self.current_task_data[task_data.run_id] = task_data
