"""
Document output tools — always-available LangChain tools that let any agent
(including the default chatbot persona, regardless of the underlying model)
produce a downloadable PDF / DOCX / XLSX / CSV / MD / TXT file during a chat.

Unlike MCP tools, these are not opt-in per agent: `get_document_tools()` is
injected into every graph build unless disabled via
`settings.DOCUMENT_TOOLS_ENABLED`.

Generated bytes are cached in-memory (FileService), uploaded to MinIO, and
recorded in the `document` table scoped to the current chat thread. Both
MinIO and DB persistence are best-effort — a failure there still returns the
file to the user for the current session; it just won't survive a service
restart.
"""

from __future__ import annotations

import json
import logging
import re
import uuid
from typing import Annotated, Any

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import BaseTool, InjectedToolArg, tool

from core.settings import settings
from service import DocumentGenerationService as docgen

logger = logging.getLogger(__name__)

DOCUMENT_FORMATS = ("pdf", "docx", "md", "txt")
SPREADSHEET_FORMATS = ("xlsx", "csv")

DOCUMENT_TOOL_PROMPT = (
    "Document output:\n"
    "- Use create_document to produce a downloadable PDF, DOCX, MD or TXT file "
    "from Markdown content (headings, paragraphs, lists, tables). It requires "
    "all three of filename, format and content — `content` must hold the "
    "complete document body as Markdown, never a summary or a description of "
    "it. A call without `content` is rejected.\n"
    "- Use create_spreadsheet to produce a downloadable XLSX or CSV file from "
    "tabular data. It requires filename, format and sheets, where `sheets` is "
    'a list of {"name": ..., "rows": [[...], ...]} objects.\n'
    "- Both tools accept an optional `options` object to style the output — "
    "theme, fonts/colors, page setup, cover page, table of contents, heading "
    "numbering, header/footer, tables, watermark (see each tool's schema for "
    "the full reference). Omit it for a sensibly-themed default; a malformed "
    "options value never fails the call, it just falls back to defaults.\n"
    "- Do NOT call these tools for greetings, small talk, or ordinary questions "
    "that only need a normal chat reply. Only call them when the user "
    "explicitly asks for a document/report/file/spreadsheet/export, or "
    "clearly asks you to save your answer as a file.\n"
    "- Example: user says 'hi' or 'merhaba' -> reply normally in the chat; do "
    "NOT call create_document or create_spreadsheet.\n"
    "- Example: user says 'create a PDF report about X' or 'bunu excel olarak "
    "hazırla' -> call the matching tool.\n"
    "- When in doubt, do not create a file — just answer in the chat.\n"
    "- After calling the tool, briefly confirm the file was created; do not "
    "repeat its full contents in the chat reply. Do NOT include the "
    "`download_url` from the tool result (or any other link to the file) in "
    "your reply — the UI already renders a clickable download card for it, "
    "and a second link in your text opens without knowing the file's real "
    "type, so it fails to preview."
)

_DOCUMENT_OPTIONS_REFERENCE = """
options (all optional; unknown/invalid values fall back to defaults and never fail the call):
  theme: default|corporate_blue|minimal_gray|academic|dark_accent
  font: {body, heading, mono, size, line_spacing, space_after}
  colors: {heading, accent, text, table_header_bg, table_header_text, table_zebra_bg, code_bg, link} (hex or CSS name)
  page: {size: A4|Letter, orientation: portrait|landscape, margins: {top, right, bottom, left} in mm}
  cover: {enabled, subtitle, project, version, date, author, organization, classification, logo}
  toc: {enabled, depth, title, mode: auto|field|static}
  numbering: {headings, max_level, separator} — renders 1 / 1.1 / 1.1.1 heading numbers
  header / footer: {left, center, right, different_first_page, rule} — text supports {page} {pages} {title} {date} {version}
  tables: {style: grid|zebra|minimal, header_bold, caption_prefix, figure_caption_prefix}
  requirement_ids: {enabled, pattern} — regex highlighting for tokens like [SRS-FUNC-001]
  watermark: {text, color}
  pdf: {bookmarks, metadata: {author, title, subject, keywords}}
  Example: {"theme": "corporate_blue", "cover": {"enabled": true, "version": "1.0"}, "toc": {"enabled": true}, "numbering": {"headings": true}}
"""

_SPREADSHEET_OPTIONS_REFERENCE = """
options (all optional; unknown/invalid values fall back to defaults and never fail the call):
  theme: default|corporate_blue|minimal_gray|academic|dark_accent
  header_row, freeze_header, autofilter, autofit_columns, zebra: bool
  column_widths: [int, ...]
  column_formats: [text|number|date|percent|currency, ...]
  column_alignments: [left|center|right, ...]
  conditional_formats: [{column, rule: equals|greater_than|less_than|contains, value, color}]
  Example: {"theme": "corporate_blue", "zebra": true, "conditional_formats": [{"column": 3, "rule": "equals", "value": "FAIL", "color": "#FFC7CE"}]}
"""

_SHORT_DOCUMENT_DESCRIPTION = (
    "Create a downloadable document (PDF, DOCX, Markdown or plain text) from "
    "Markdown content. Requires filename, format, content. Optional: title, "
    "options (theme/page/header/footer/cover/toc/numbering/tables/watermark — "
    "omit for a sensibly-themed default)."
)
_SHORT_SPREADSHEET_DESCRIPTION = (
    "Create a downloadable spreadsheet (XLSX or CSV) from tabular data. "
    "Requires filename, format, sheets. Optional: options (theme, header "
    "styling, column widths/formats/alignments, conditional formatting)."
)


def _download_url(file_id: str) -> str:
    return f"/api/chat/file/{file_id}?download=1"


# Keys smaller models reach for instead of `content` when passing the body.
_CONTENT_ALIASES = (
    "content",
    "text",
    "body",
    "markdown",
    "md",
    "document",
    "document_content",
    "content_markdown",
)

# Some models emit the body wrapped in pseudo-XML inside another argument,
# e.g. {"filename": "...", "title": "<content># Başlık\n...</content>"}. The
# tags also turn up unpaired, with the provider's parser having eaten the other
# half, so opening and closing markers are matched independently.
_CONTENT_TAG_RE = re.compile(r"</?\s*(content|document|body|markdown|tool_call)\s*>", re.IGNORECASE)

# Arguments that are never the document body.
_NON_BODY_KEYS = frozenset({"filename", "format", "title", "name", "path"})

# A stray argument this long, spanning several lines, is the body rather than a
# stray label — short values are left alone so a description is never promoted.
_BODY_MIN_LENGTH = 200


def strip_content_markup(text: str) -> str:
    """Remove pseudo-XML content/tool-call markers a model left in the body."""
    return _CONTENT_TAG_RE.sub("", text).strip()


# Top-level DocumentOptions section names — see service.documents.options.
_OPTIONS_TOP_LEVEL_KEYS = frozenset(
    {
        "theme",
        "font",
        "colors",
        "page",
        "cover",
        "toc",
        "numbering",
        "header",
        "footer",
        "front_matter",
        "tables",
        "requirement_ids",
        "watermark",
        "pdf",
    }
)


def _gather_stray_options(args: dict[str, Any]) -> dict[str, Any]:
    """Fold style keys a model placed at the top level (e.g. `theme=...`
    alongside `filename`/`format`/`content`) into `options`, instead of
    leaving them as unknown arguments the schema would reject.
    """
    stray = {key: args[key] for key in _OPTIONS_TOP_LEVEL_KEYS if key in args}
    if not stray:
        return args

    repaired = {key: value for key, value in args.items() if key not in stray}
    existing = args.get("options")
    if existing is None:
        repaired["options"] = stray
    elif isinstance(existing, dict):
        repaired["options"] = {**stray, **existing}
    else:
        repaired["options"] = existing
    return repaired


def recover_document_tool_args(args: dict[str, Any]) -> dict[str, Any]:
    """Repair a `create_document` call that put the body somewhere else, or
    style keys somewhere other than `options`.

    Local models pass the document under `text`/`body`, or inline it as
    `<content>…</content>` — often with only one half of the tag pair surviving
    the provider's own parser. Rejecting those costs the user a full
    regeneration of a long document, so recover the body where the intent is
    clear and leave anything ambiguous to normal validation. Style keys
    dropped at the top level (`theme=...`) are gathered into `options`.

    Only ever *adds* `content` (and cleans markup out of it); the document body
    is never invented from a short unrelated argument.
    """
    if not isinstance(args, dict):
        return args

    return _recover_content(_gather_stray_options(args))


def _recover_content(args: dict[str, Any]) -> dict[str, Any]:
    repaired = dict(args)

    existing = repaired.get("content")
    if isinstance(existing, str) and existing.strip():
        cleaned = strip_content_markup(existing)
        if cleaned and cleaned != existing:
            repaired["content"] = cleaned
            return repaired
        return args

    for alias in _CONTENT_ALIASES:
        value = repaired.get(alias)
        if isinstance(value, str) and value.strip():
            repaired["content"] = strip_content_markup(value)
            if alias != "content":
                repaired.pop(alias, None)
            return repaired

    # A full <content>…</content> pair is unambiguous wherever it appears.
    for key, value in list(repaired.items()):
        if not isinstance(value, str):
            continue
        match = re.search(
            r"<\s*(content|document|body)\s*>(.*?)</\s*\1\s*>", value, re.DOTALL | re.IGNORECASE
        )
        if not match or not match.group(2).strip():
            continue
        repaired["content"] = match.group(2).strip()
        remainder = strip_content_markup(value.replace(match.group(0), ""))
        if remainder:
            repaired[key] = remainder
        else:
            repaired.pop(key, None)
        return repaired

    # Otherwise take a stray argument that carries a lone marker, or one long
    # enough that it can only be the document itself.
    for key, value in list(repaired.items()):
        if key in _NON_BODY_KEYS or not isinstance(value, str):
            continue
        looks_like_body = _CONTENT_TAG_RE.search(value) or (
            len(value) >= _BODY_MIN_LENGTH and "\n" in value
        )
        if not looks_like_body:
            continue
        cleaned = strip_content_markup(value)
        if not cleaned:
            continue
        repaired["content"] = cleaned
        repaired.pop(key, None)
        return repaired

    return args


def _emit_stream_event(payload: dict[str, Any]) -> None:
    """Best-effort live SSE packet from inside a tool call.

    A node's updates only reach the stream once the whole node returns. The
    default chatbot graph runs its entire tool loop inside one node, so without
    these the UI learns the file exists only after the model has already
    written its closing answer. Failing here is never fatal — the ToolMessage
    still carries the same information at node end.
    """
    try:
        from langgraph.config import get_stream_writer

        writer = get_stream_writer()
        if writer:
            writer(payload)
    except Exception as exc:
        logger.debug("Could not emit document stream event: %s", exc)


def _emit_rendering_started(tool_name: str, filename: str, fmt: str, chars: int) -> None:
    _emit_stream_event(
        {
            "type": "document_generation_progress",
            "tool_name": tool_name,
            "filename": filename,
            "format": fmt,
            "phase": "rendering",
            "chars": chars,
        }
    )


def _emit_generation_failed(tool_name: str, filename: str, fmt: str, error: str) -> None:
    _emit_stream_event(
        {
            "type": "document_generation_end",
            "tool_name": tool_name,
            "filename": filename,
            "format": fmt,
            "status": "error",
            "error": error,
        }
    )


def _configurable(config: RunnableConfig) -> dict[str, Any]:
    return (config or {}).get("configurable", {}) or {}


async def _persist_generated_file(
    *,
    filename: str,
    fmt: str,
    data: bytes,
    mime_type: str,
    config: RunnableConfig,
    tool_name: str,
) -> str:
    """Store bytes in the in-memory cache, MinIO, and the document table.

    Returns the JSON-encoded payload the LLM sees as the tool result.
    """
    from service.FileService import store_file

    configurable = _configurable(config)
    user_id = str(configurable.get("user_id") or "anonymous")
    thread_id = configurable.get("thread_id")

    file_id = uuid.uuid4().hex
    store_file(file_id, data, mime_type, filename)

    object_key = ""
    try:
        from service.MinioService import upload_file as minio_upload

        object_key = minio_upload(
            user_id=user_id,
            file_id=file_id,
            filename=filename,
            data=data,
            mime_type=mime_type,
        )
    except Exception as exc:
        logger.warning("Could not upload generated file %s to MinIO: %s", file_id, exc)

    try:
        from core.db.repositories.document_repo import DocumentRepository
        from service.FileService import mime_to_chat_file_type

        await DocumentRepository().create(
            file_id=file_id,
            user_id=user_id,
            filename=filename,
            mime_type=mime_type,
            chat_file_type=mime_to_chat_file_type(mime_type),
            size_bytes=len(data),
            minio_object_key=object_key,
            thread_id=thread_id,
        )
    except Exception as exc:
        logger.warning("Could not persist generated file %s to document table: %s", file_id, exc)

    payload = {
        "__generated_file__": True,
        "file_id": file_id,
        "filename": filename,
        "mime_type": mime_type,
        "size_bytes": len(data),
        "download_url": _download_url(file_id),
    }

    # Publish the finished file straight away so the UI can swap its progress
    # skeleton for the file card now, rather than when the node returns.
    from service.GeneratedFilePacket import build_generated_file_packet_obj

    _emit_stream_event(build_generated_file_packet_obj(payload))
    _emit_stream_event(
        {
            "type": "document_generation_end",
            "tool_name": tool_name,
            "filename": filename,
            "format": fmt,
            "status": "success",
            "error": None,
        }
    )

    return json.dumps(payload)


@tool
async def create_document(
    filename: str,
    format: str,
    content: str,
    config: Annotated[RunnableConfig, InjectedToolArg],
    title: str | None = None,
    options: dict[str, Any] | str | None = None,
) -> str:
    """Create a downloadable document (PDF, DOCX, Markdown or plain text) from Markdown content.

    Args:
        filename: Base file name, without or with the correct extension.
        format: One of "pdf", "docx", "md", "txt". Any other value is rejected.
        content: The document body as Markdown (headings, paragraphs, lists,
            pipe tables, and fenced code blocks are supported).
        title: Optional document title, rendered above the content.
        options: Optional style/layout configuration (theme, fonts, colors,
            page setup, cover page, table of contents, heading numbering,
            header/footer, tables, watermark) — see the options reference
            appended to this tool's description. Omit for a sensibly-themed
            default; any unrecognized or invalid field silently falls back
            to its default rather than failing the call.

    Returns:
        A short confirmation on success, or an error description on failure.
    """
    if format not in DOCUMENT_FORMATS:
        return f"Error: unsupported document format '{format}'. Use one of: {', '.join(DOCUMENT_FORMATS)}."

    safe_filename = docgen.sanitize_filename(filename, format)
    mime_type = docgen.mime_for_format(format)
    _emit_rendering_started("create_document", safe_filename, format, len(content or ""))
    parsed_options = docgen.parse_document_options(options)

    try:
        if format == "pdf":
            data = docgen.render_pdf(title, content, options=parsed_options)
        elif format == "docx":
            data = docgen.render_docx(title, content, options=parsed_options)
        else:
            data = docgen.render_markdown_text(title, content, options=parsed_options)
    except ValueError as exc:
        _emit_generation_failed("create_document", safe_filename, format, str(exc))
        return f"Error: could not create document: {exc}"
    except Exception as exc:
        logger.error("Document rendering failed for format=%s: %s", format, exc)
        _emit_generation_failed("create_document", safe_filename, format, str(exc))
        return f"Error: could not create document: {exc}"

    try:
        return await _persist_generated_file(
            filename=safe_filename,
            fmt=format,
            data=data,
            mime_type=mime_type,
            config=config,
            tool_name="create_document",
        )
    except ValueError as exc:
        _emit_generation_failed("create_document", safe_filename, format, str(exc))
        return f"Error: could not create document: {exc}"


@tool
async def create_spreadsheet(
    filename: str,
    format: str,
    sheets: list[dict[str, Any]],
    config: Annotated[RunnableConfig, InjectedToolArg],
    options: dict[str, Any] | str | None = None,
) -> str:
    """Create a downloadable spreadsheet (XLSX or CSV) from tabular data.

    Args:
        filename: Base file name, without or with the correct extension.
        format: One of "xlsx", "csv". Any other value is rejected.
        sheets: One or more sheets, each `{"name": str, "rows": [[...], ...]}`.
            For CSV output, only the first sheet's rows are used.
        options: Optional styling (theme, header row, freeze pane, autofilter,
            zebra striping, column widths/formats/alignments, conditional
            formatting) — see the options reference appended to this tool's
            description. XLSX only; ignored for CSV. Any unrecognized or
            invalid field silently falls back to its default.

    Returns:
        A short confirmation on success, or an error description on failure.
    """
    if format not in SPREADSHEET_FORMATS:
        return (
            f"Error: unsupported spreadsheet format '{format}'. "
            f"Use one of: {', '.join(SPREADSHEET_FORMATS)}."
        )

    safe_filename = docgen.sanitize_filename(filename, format)
    mime_type = docgen.mime_for_format(format)
    row_count = sum(len(sheet.get("rows") or []) for sheet in sheets or [])
    _emit_rendering_started("create_spreadsheet", safe_filename, format, row_count)

    try:
        if format == "xlsx":
            data = docgen.render_xlsx(sheets, options=docgen.parse_spreadsheet_options(options))
        else:
            first_sheet = sheets[0] if sheets else None
            if not first_sheet or not first_sheet.get("rows"):
                raise ValueError("sheets must contain at least one sheet with rows")
            data = docgen.render_csv(first_sheet["rows"])
    except ValueError as exc:
        _emit_generation_failed("create_spreadsheet", safe_filename, format, str(exc))
        return f"Error: could not create spreadsheet: {exc}"
    except Exception as exc:
        logger.error("Spreadsheet rendering failed for format=%s: %s", format, exc)
        _emit_generation_failed("create_spreadsheet", safe_filename, format, str(exc))
        return f"Error: could not create spreadsheet: {exc}"

    try:
        return await _persist_generated_file(
            filename=safe_filename,
            fmt=format,
            data=data,
            mime_type=mime_type,
            config=config,
            tool_name="create_spreadsheet",
        )
    except ValueError as exc:
        _emit_generation_failed("create_spreadsheet", safe_filename, format, str(exc))
        return f"Error: could not create spreadsheet: {exc}"


create_document.description += _DOCUMENT_OPTIONS_REFERENCE
create_spreadsheet.description += _SPREADSHEET_OPTIONS_REFERENCE


def get_document_tools() -> list[BaseTool]:
    """Return the always-on document tools, or [] if disabled via settings.

    The `options` reference costs ~350 tokens per request; when
    `DOCUMENT_TOOLS_RICH_OPTIONS` is off, token-sensitive or small
    local-model setups get a short description instead — `options` still
    works, the model just isn't told about it in detail.
    """
    if not settings.DOCUMENT_TOOLS_ENABLED:
        return []
    if settings.DOCUMENT_TOOLS_RICH_OPTIONS:
        return [create_document, create_spreadsheet]
    return [
        create_document.model_copy(update={"description": _SHORT_DOCUMENT_DESCRIPTION}),
        create_spreadsheet.model_copy(update={"description": _SHORT_SPREADSHEET_DESCRIPTION}),
    ]


def bind_document_tools(model: BaseChatModel, tools: list[BaseTool]) -> tuple[Any, bool]:
    """Bind tools to a model, falling back gracefully if tool-calling is unsupported.

    Returns (possibly-bound model, whether binding succeeded). Callers should
    only wire up a tool-execution loop when the second element is True.
    """
    try:
        return model.bind_tools(tools), True
    except Exception as exc:
        logger.warning("Model does not support tool binding, disabling tools: %s", exc)
        return model, False
