"""
Document output tools — always-available LangChain tools that let any agent
(including the default chatbot persona, regardless of the underlying model)
produce a downloadable PDF / DOCX / XLSX / CSV / MD / TXT file during a chat.

Unlike MCP tools, these are not opt-in per agent: `get_document_tools()` is
injected into every graph build unless disabled via
`settings.DOCUMENT_TOOLS_ENABLED`.

Generated bytes are cached in-memory (FileService), uploaded to MinIO, and
recorded in the `document` table scoped to the current chat thread. Both
MinIO and DB persistence are best-effort — a failure there still returns the
file to the user for the current session; it just won't survive a service
restart.
"""

from __future__ import annotations

import json
import logging
import uuid
from typing import Annotated, Any

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import BaseTool, InjectedToolArg, tool

from core.settings import settings
from service import DocumentGenerationService as docgen

logger = logging.getLogger(__name__)

DOCUMENT_FORMATS = ("pdf", "docx", "md", "txt")
SPREADSHEET_FORMATS = ("xlsx", "csv")

DOCUMENT_TOOL_PROMPT = (
    "Document output:\n"
    "- Use create_document to produce a downloadable PDF, DOCX, MD or TXT file "
    "from Markdown content (headings, paragraphs, lists, tables).\n"
    "- Use create_spreadsheet to produce a downloadable XLSX or CSV file from "
    "tabular data (one or more named sheets of rows).\n"
    "- Do NOT call these tools for greetings, small talk, or ordinary questions "
    "that only need a normal chat reply. Only call them when the user "
    "explicitly asks for a document/report/file/spreadsheet/export, or "
    "clearly asks you to save your answer as a file.\n"
    "- Example: user says 'hi' or 'merhaba' -> reply normally in the chat; do "
    "NOT call create_document or create_spreadsheet.\n"
    "- Example: user says 'create a PDF report about X' or 'bunu excel olarak "
    "hazırla' -> call the matching tool.\n"
    "- When in doubt, do not create a file — just answer in the chat.\n"
    "- After calling the tool, briefly confirm the file was created; do not "
    "repeat its full contents in the chat reply."
)


def _download_url(file_id: str) -> str:
    return f"/api/chat/file/{file_id}?download=1"


def _configurable(config: RunnableConfig) -> dict[str, Any]:
    return (config or {}).get("configurable", {}) or {}


async def _persist_generated_file(
    *,
    filename: str,
    fmt: str,
    data: bytes,
    mime_type: str,
    config: RunnableConfig,
) -> str:
    """Store bytes in the in-memory cache, MinIO, and the document table.

    Returns the JSON-encoded payload the LLM sees as the tool result.
    """
    from service.FileService import store_file

    configurable = _configurable(config)
    user_id = str(configurable.get("user_id") or "anonymous")
    thread_id = configurable.get("thread_id")

    file_id = uuid.uuid4().hex
    store_file(file_id, data, mime_type, filename)

    object_key = ""
    try:
        from service.MinioService import upload_file as minio_upload

        object_key = minio_upload(
            user_id=user_id,
            file_id=file_id,
            filename=filename,
            data=data,
            mime_type=mime_type,
        )
    except Exception as exc:
        logger.warning("Could not upload generated file %s to MinIO: %s", file_id, exc)

    try:
        from core.db.repositories.document_repo import DocumentRepository
        from service.FileService import mime_to_chat_file_type

        await DocumentRepository().create(
            file_id=file_id,
            user_id=user_id,
            filename=filename,
            mime_type=mime_type,
            chat_file_type=mime_to_chat_file_type(mime_type),
            size_bytes=len(data),
            minio_object_key=object_key,
            thread_id=thread_id,
        )
    except Exception as exc:
        logger.warning("Could not persist generated file %s to document table: %s", file_id, exc)

    payload = {
        "__generated_file__": True,
        "file_id": file_id,
        "filename": filename,
        "mime_type": mime_type,
        "size_bytes": len(data),
        "download_url": _download_url(file_id),
    }
    return json.dumps(payload)


@tool
async def create_document(
    filename: str,
    format: str,
    content: str,
    config: Annotated[RunnableConfig, InjectedToolArg],
    title: str | None = None,
) -> str:
    """Create a downloadable document (PDF, DOCX, Markdown or plain text) from Markdown content.

    Args:
        filename: Base file name, without or with the correct extension.
        format: One of "pdf", "docx", "md", "txt". Any other value is rejected.
        content: The document body as Markdown (headings, paragraphs, lists,
            pipe tables, and fenced code blocks are supported).
        title: Optional document title, rendered above the content.

    Returns:
        A short confirmation on success, or an error description on failure.
    """
    if format not in DOCUMENT_FORMATS:
        return f"Error: unsupported document format '{format}'. Use one of: {', '.join(DOCUMENT_FORMATS)}."

    try:
        if format == "pdf":
            data = docgen.render_pdf(title, content)
        elif format == "docx":
            data = docgen.render_docx(title, content)
        else:
            data = docgen.render_markdown_text(title, content)
    except ValueError as exc:
        return f"Error: could not create document: {exc}"
    except Exception as exc:
        logger.error("Document rendering failed for format=%s: %s", format, exc)
        return f"Error: could not create document: {exc}"

    safe_filename = docgen.sanitize_filename(filename, format)
    mime_type = docgen.mime_for_format(format)

    try:
        return await _persist_generated_file(
            filename=safe_filename,
            fmt=format,
            data=data,
            mime_type=mime_type,
            config=config,
        )
    except ValueError as exc:
        return f"Error: could not create document: {exc}"


@tool
async def create_spreadsheet(
    filename: str,
    format: str,
    sheets: list[dict[str, Any]],
    config: Annotated[RunnableConfig, InjectedToolArg],
) -> str:
    """Create a downloadable spreadsheet (XLSX or CSV) from tabular data.

    Args:
        filename: Base file name, without or with the correct extension.
        format: One of "xlsx", "csv". Any other value is rejected.
        sheets: One or more sheets, each `{"name": str, "rows": [[...], ...]}`.
            For CSV output, only the first sheet's rows are used.

    Returns:
        A short confirmation on success, or an error description on failure.
    """
    if format not in SPREADSHEET_FORMATS:
        return (
            f"Error: unsupported spreadsheet format '{format}'. "
            f"Use one of: {', '.join(SPREADSHEET_FORMATS)}."
        )

    try:
        if format == "xlsx":
            data = docgen.render_xlsx(sheets)
        else:
            first_sheet = sheets[0] if sheets else None
            if not first_sheet or not first_sheet.get("rows"):
                raise ValueError("sheets must contain at least one sheet with rows")
            data = docgen.render_csv(first_sheet["rows"])
    except ValueError as exc:
        return f"Error: could not create spreadsheet: {exc}"
    except Exception as exc:
        logger.error("Spreadsheet rendering failed for format=%s: %s", format, exc)
        return f"Error: could not create spreadsheet: {exc}"

    safe_filename = docgen.sanitize_filename(filename, format)
    mime_type = docgen.mime_for_format(format)

    try:
        return await _persist_generated_file(
            filename=safe_filename,
            fmt=format,
            data=data,
            mime_type=mime_type,
            config=config,
        )
    except ValueError as exc:
        return f"Error: could not create spreadsheet: {exc}"


def get_document_tools() -> list[BaseTool]:
    """Return the always-on document tools, or [] if disabled via settings."""
    if not settings.DOCUMENT_TOOLS_ENABLED:
        return []
    return [create_document, create_spreadsheet]


def bind_document_tools(
    model: BaseChatModel, tools: list[BaseTool]
) -> tuple[Any, bool]:
    """Bind tools to a model, falling back gracefully if tool-calling is unsupported.

    Returns (possibly-bound model, whether binding succeeded). Callers should
    only wire up a tool-execution loop when the second element is True.
    """
    try:
        return model.bind_tools(tools), True
    except Exception as exc:
        logger.warning("Model does not support tool binding, disabling tools: %s", exc)
        return model, False
