/**
 * Tests for compile.ts — FlowSpec <-> xyflow round-trip.
 *
 * The fixture is not hand-written — it was generated by literally calling
 * the backend's own FlowSpec.model_dump(by_alias=True, mode="json"):
 *
 *   uv run python -c "
 *     from models.flows import FlowSpec
 *     spec = FlowSpec.model_validate({...})
 *     print(json.dumps(spec.model_dump(by_alias=True, mode='json')))
 *   " > flowSpecFixture.json
 *
 * so the round-trip is proven against the real wire shape, not a client-side
 * guess of what it looks like.
 *
 * Brief: .tmp/flow-canvas-task-23-brief.md
 */

import type { WireFlowSpec, WireFlowNode, WireFlowEdge } from "../types/flow";
import { fromFlowSpec, toFlowSpec, diffFlowSpecs } from "../utils/compile";
import fixture from "./__fixtures__/flowSpecFixture.json";

const REAL_SPEC = fixture as WireFlowSpec;

describe("compile — round-trip stability (23.1)", () => {
  // The fixture's node/edge arrays are already in id-alphabetical order —
  // deliberately, since toFlowSpec canonicalizes to that order regardless
  // of input order (23.7's guarantee). "Byte-identical" here means
  // "identical to the canonical form", which coincides with the original
  // file because the file already IS canonical, not because compile.ts
  // preserves arbitrary input order.
  it("an unedited spec round-trips byte-identical", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const result = toFlowSpec(nodes, edges, viewport);

    expect(result).toEqual(REAL_SPEC);
  });
});

describe("compile — wire-format field casing (23.2, 23.3)", () => {
  it("22.2/23.2 — edge handles use camelCase on the wire", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const result = toFlowSpec(nodes, edges, viewport);

    for (const edge of result.edges) {
      expect(edge).toHaveProperty("sourceHandle");
      expect(edge).toHaveProperty("targetHandle");
      expect(edge).not.toHaveProperty("source_handle");
      expect(edge).not.toHaveProperty("target_handle");
    }
  });

  it("23.3 — node template_version uses snake_case on the wire", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const result = toFlowSpec(nodes, edges, viewport);

    for (const node of result.nodes) {
      expect(node).toHaveProperty("template_version");
      expect(node).not.toHaveProperty("templateVersion");
    }
  });
});

describe("compile — viewport (23.4)", () => {
  it("round-trips pan/zoom", () => {
    const { viewport } = fromFlowSpec(REAL_SPEC);
    expect(viewport).toEqual({ x: 10, y: 20, zoom: 1.5 });

    const result = toFlowSpec([], [], viewport);
    expect(result.viewport).toEqual({ x: 10, y: 20, zoom: 1.5 });
  });

  it("a null viewport reads in as a sensible default", () => {
    const specWithoutViewport: WireFlowSpec = { ...REAL_SPEC, viewport: null };
    const { viewport } = fromFlowSpec(specWithoutViewport);

    expect(viewport).toEqual({ x: 0, y: 0, zoom: 1 });
  });
});

describe("compile — no default-baking (23.5, the R1 client half)", () => {
  it("a node's absent optional values stay absent after round-trip", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const result = toFlowSpec(nodes, edges, viewport);

    // in-1 / out-1 have empty `values` in the fixture — must still be
    // empty, never filled in with a template default the client doesn't
    // (and shouldn't) know about.
    const inNode = result.nodes.find((n) => n.id === "in-1")!;
    expect(inNode.values).toEqual({});
  });
});

describe("compile — transient xyflow fields are dropped (23.6)", () => {
  it("selected/dragging/measured never reach the serialized spec", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const withRuntimeState = nodes.map((n) => ({
      ...n,
      selected: true,
      dragging: true,
      measured: { width: 200, height: 80 },
    }));

    const result = toFlowSpec(withRuntimeState, edges, viewport);

    for (const node of result.nodes) {
      expect(node).not.toHaveProperty("selected");
      expect(node).not.toHaveProperty("dragging");
      expect(node).not.toHaveProperty("measured");
    }
  });
});

describe("compile — stable under reordering (23.7)", () => {
  it("selecting/reordering nodes at runtime does not change the serialized order or content", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const reversed = [...nodes].reverse();

    const result = toFlowSpec(reversed, edges, viewport);

    expect(result).toEqual(REAL_SPEC);
  });
});

describe("compile — position rounding (23.8)", () => {
  it("sub-pixel drag drift does not produce a diff", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const drifted = nodes.map((n) => ({
      ...n,
      position: { x: n.position.x + 0.0001, y: n.position.y - 0.0001 },
    }));

    const result = toFlowSpec(drifted, edges, viewport);

    expect(result).toEqual(REAL_SPEC);
  });

  it("a real position change of a whole pixel is preserved", () => {
    const { nodes, edges, viewport } = fromFlowSpec(REAL_SPEC);
    const moved = nodes.map((n) =>
      n.id === "in-1" ? { ...n, position: { x: 50, y: 60 } } : n
    );

    const result = toFlowSpec(moved, edges, viewport);

    expect(result.nodes.find((n) => n.id === "in-1")!.position).toEqual({
      x: 50,
      y: 60,
    });
  });
});

describe("compile — unknown component types survive (23.9, data-loss guard)", () => {
  it("a node of a type this client build doesn't recognize is preserved, not dropped", () => {
    const specWithUnknownType: WireFlowSpec = {
      ...REAL_SPEC,
      nodes: [
        ...REAL_SPEC.nodes,
        {
          id: "future-1",
          type: "SomeFutureComponentType",
          template_version: 7,
          position: { x: 999, y: 999 },
          values: { some_future_field: "opaque" },
        },
      ],
    };

    const { nodes, edges, viewport } = fromFlowSpec(specWithUnknownType);
    const result = toFlowSpec(nodes, edges, viewport);

    const survived = result.nodes.find((n) => n.id === "future-1");
    expect(survived).toBeDefined();
    expect(survived).toEqual({
      id: "future-1",
      type: "SomeFutureComponentType",
      template_version: 7,
      position: { x: 999, y: 999 },
      values: { some_future_field: "opaque" },
    });
  });
});

function node(overrides: Partial<WireFlowNode> = {}): WireFlowNode {
  return {
    id: "chatbot-1",
    type: "Chatbot",
    template_version: 1,
    position: { x: 0, y: 0 },
    values: {},
    ...overrides,
  };
}

function edge(overrides: Partial<WireFlowEdge> = {}): WireFlowEdge {
  return {
    id: "edge-1",
    source: "chatinput-1",
    sourceHandle: "message",
    target: "chatbot-1",
    targetHandle: "message",
    ...overrides,
  };
}

function spec(nodes: WireFlowNode[], edges: WireFlowEdge[] = []): WireFlowSpec {
  return { version: "1.0", nodes, edges, viewport: { x: 0, y: 0, zoom: 1 } };
}

describe("diffFlowSpecs — no changes", () => {
  it("returns nothing for two identical specs", () => {
    const a = spec([node()], [edge()]);
    const b = spec([node()], [edge()]);
    expect(diffFlowSpecs(a, b)).toEqual([]);
  });
});

describe("diffFlowSpecs — structural changes", () => {
  it("reports an added node", () => {
    const a = spec([node({ id: "chatbot-1" })]);
    const b = spec([
      node({ id: "chatbot-1" }),
      node({ id: "chatoutput-1", type: "ChatOutput" }),
    ]);
    expect(diffFlowSpecs(a, b)).toEqual([
      { kind: "node-added", nodeId: "chatoutput-1", nodeType: "ChatOutput" },
    ]);
  });

  it("reports a removed node", () => {
    const a = spec([
      node({ id: "chatbot-1" }),
      node({ id: "chatoutput-1", type: "ChatOutput" }),
    ]);
    const b = spec([node({ id: "chatbot-1" })]);
    expect(diffFlowSpecs(a, b)).toEqual([
      { kind: "node-removed", nodeId: "chatoutput-1", nodeType: "ChatOutput" },
    ]);
  });

  it("reports an added edge, labelled with both endpoints' component types", () => {
    const a = spec(
      [
        node({ id: "chatinput-1", type: "ChatInput" }),
        node({ id: "chatbot-1" }),
      ],
      []
    );
    const b = spec(
      [
        node({ id: "chatinput-1", type: "ChatInput" }),
        node({ id: "chatbot-1" }),
      ],
      [edge()]
    );
    expect(diffFlowSpecs(a, b)).toEqual([
      {
        kind: "edge-added",
        edgeId: "edge-1",
        sourceNodeId: "chatinput-1",
        sourceType: "ChatInput",
        targetNodeId: "chatbot-1",
        targetType: "Chatbot",
      },
    ]);
  });

  it("reports a removed edge", () => {
    const a = spec(
      [
        node({ id: "chatinput-1", type: "ChatInput" }),
        node({ id: "chatbot-1" }),
      ],
      [edge()]
    );
    const b = spec(
      [
        node({ id: "chatinput-1", type: "ChatInput" }),
        node({ id: "chatbot-1" }),
      ],
      []
    );
    expect(diffFlowSpecs(a, b)).toEqual([
      {
        kind: "edge-removed",
        edgeId: "edge-1",
        sourceNodeId: "chatinput-1",
        sourceType: "ChatInput",
        targetNodeId: "chatbot-1",
        targetType: "Chatbot",
      },
    ]);
  });

  it("does not report a node whose position moved as a change", () => {
    const a = spec([node({ position: { x: 0, y: 0 } })]);
    const b = spec([node({ position: { x: 400, y: 250 } })]);
    expect(diffFlowSpecs(a, b)).toEqual([]);
  });
});

describe("diffFlowSpecs — field value changes", () => {
  it("reports a changed field with old and new values", () => {
    const a = spec([node({ values: { temperature: 0.3 } })]);
    const b = spec([node({ values: { temperature: 0.5 } })]);
    expect(diffFlowSpecs(a, b)).toEqual([
      {
        kind: "field-changed",
        nodeId: "chatbot-1",
        nodeType: "Chatbot",
        field: "temperature",
        oldValue: 0.3,
        newValue: 0.5,
      },
    ]);
  });

  it("reports a field that was added", () => {
    const a = spec([node({ values: {} })]);
    const b = spec([node({ values: { model: "gpt-4o" } })]);
    expect(diffFlowSpecs(a, b)).toEqual([
      {
        kind: "field-changed",
        nodeId: "chatbot-1",
        nodeType: "Chatbot",
        field: "model",
        oldValue: undefined,
        newValue: "gpt-4o",
      },
    ]);
  });

  it("reports a field that was cleared", () => {
    const a = spec([node({ values: { model: "gpt-4o" } })]);
    const b = spec([node({ values: {} })]);
    expect(diffFlowSpecs(a, b)).toEqual([
      {
        kind: "field-changed",
        nodeId: "chatbot-1",
        nodeType: "Chatbot",
        field: "model",
        oldValue: "gpt-4o",
        newValue: undefined,
      },
    ]);
  });

  it("ignores the sticky note color field as cosmetic", () => {
    const a = spec([
      node({
        id: "note-1",
        type: "note",
        values: { text: "hi", color: "yellow" },
      }),
    ]);
    const b = spec([
      node({
        id: "note-1",
        type: "note",
        values: { text: "hi", color: "blue" },
      }),
    ]);
    expect(diffFlowSpecs(a, b)).toEqual([]);
  });

  it("still reports sticky note text changes", () => {
    const a = spec([
      node({
        id: "note-1",
        type: "note",
        values: { text: "hi", color: "yellow" },
      }),
    ]);
    const b = spec([
      node({
        id: "note-1",
        type: "note",
        values: { text: "bye", color: "yellow" },
      }),
    ]);
    expect(diffFlowSpecs(a, b)).toEqual([
      {
        kind: "field-changed",
        nodeId: "note-1",
        nodeType: "note",
        field: "text",
        oldValue: "hi",
        newValue: "bye",
      },
    ]);
  });

  it("does not report a node present in only one spec as having field changes", () => {
    const a = spec([]);
    const b = spec([node({ values: { temperature: 0.7 } })]);
    // Only the add shows up — not also a fabricated "temperature changed
    // from nothing" entry for a node that didn't exist before.
    expect(diffFlowSpecs(a, b)).toEqual([
      { kind: "node-added", nodeId: "chatbot-1", nodeType: "Chatbot" },
    ]);
  });
});

describe("diffFlowSpecs — template version upgrades", () => {
  it("reports a node's template_version changing", () => {
    const a = spec([node({ template_version: 1 })]);
    const b = spec([node({ template_version: 2 })]);
    expect(diffFlowSpecs(a, b)).toEqual([
      {
        kind: "template-upgraded",
        nodeId: "chatbot-1",
        nodeType: "Chatbot",
        oldVersion: 1,
        newVersion: 2,
      },
    ]);
  });
});

describe("diffFlowSpecs — ordering", () => {
  it("orders entries by node/edge id so the list is stable across runs", () => {
    const a = spec([node({ id: "z-node" }), node({ id: "a-node" })]);
    const b = spec([
      node({ id: "z-node", values: { x: 1 } }),
      node({ id: "a-node", values: { x: 1 } }),
    ]);
    const result = diffFlowSpecs(a, b);
    expect(result.map((r) => (r as { nodeId: string }).nodeId)).toEqual([
      "a-node",
      "z-node",
    ]);
  });
});
