/**
 * Tests for handleTypes.ts — the client-side mirror of
 * apps/agent-service/src/domain/flows/handle_types.py.
 *
 * The compatibility order is load-bearing and was corrected by a real test
 * failure during P1 Task 3 (design spec amendment F): Trigger isolation
 * must outrank the Data catch-all, or a Trigger (a pure signal, no payload)
 * would be treated as satisfying a Data port.
 *
 * 22.6 guards against silent drift between server and client: it replays
 * every one of the 9x9 PortType pairs against `handleCompatibilityFixture.json`,
 * which is not hand-transcribed — it was generated by literally invoking
 * the backend's own `is_compatible()`:
 *
 *   uv run python -c "
 *     from domain.flows.handle_types import is_compatible
 *     from models.flows import PortType
 *     ... dump every (source, target) -> compatible triple as JSON ...
 *   " > handleCompatibilityFixture.json
 *
 * Re-run that whenever handle_types.py changes; this test then tells you
 * immediately if the client fell out of sync.
 *
 * Brief: .tmp/flow-canvas-task-22-brief.md
 */

import type { PortType } from "../types/flow";
import { handlesCompatible, isCompatible } from "../utils/handleTypes";
import fixture from "./__fixtures__/handleCompatibilityFixture.json";

const ALL_PORT_TYPES: PortType[] = [
  "Message",
  "Text",
  "Documents",
  "Tools",
  "Model",
  "Memory",
  "Agent",
  "Data",
  "Trigger",
];

describe("isCompatible — mirrors handle_types.py", () => {
  it("22.1 — every port type is compatible with itself", () => {
    for (const port of ALL_PORT_TYPES) {
      expect(isCompatible(port, port)).toBe(true);
    }
  });

  it("22.2 — Trigger isolation outranks the Data catch-all (amendment F)", () => {
    for (const port of ALL_PORT_TYPES) {
      if (port === "Trigger") continue;
      expect(isCompatible("Trigger", port)).toBe(false);
      expect(isCompatible(port, "Trigger")).toBe(false);
    }
  });

  it("22.3 — Data accepts any non-Trigger source", () => {
    for (const port of ALL_PORT_TYPES) {
      if (port === "Trigger") continue;
      expect(isCompatible(port, "Data")).toBe(true);
    }
  });

  it("22.4 — Data as a source is rejected by any non-Data target", () => {
    for (const port of ALL_PORT_TYPES) {
      if (port === "Data") continue;
      expect(isCompatible("Data", port)).toBe(false);
    }
  });

  it("22.5 — Message coerces to Text but not the reverse", () => {
    expect(isCompatible("Message", "Text")).toBe(true);
    expect(isCompatible("Text", "Message")).toBe(false);
  });

  it("22.6 — the full 9x9 matrix matches the backend-generated fixture", () => {
    expect(fixture).toHaveLength(81);
    for (const { source, target, compatible } of fixture as Array<{
      source: PortType;
      target: PortType;
      compatible: boolean;
    }>) {
      expect(isCompatible(source, target)).toBe(compatible);
    }
  });

  it("compatibility is total — every pair returns a boolean", () => {
    for (const source of ALL_PORT_TYPES) {
      for (const target of ALL_PORT_TYPES) {
        expect(typeof isCompatible(source, target)).toBe("boolean");
      }
    }
  });
});

describe("handlesCompatible — 22.10, multi-type handles", () => {
  it("is compatible if any pair among the two type lists matches", () => {
    expect(handlesCompatible(["Message"], ["Data"])).toBe(true);
    expect(handlesCompatible(["Trigger", "Message"], ["Text"])).toBe(true);
    expect(handlesCompatible(["Trigger"], ["Data"])).toBe(false);
  });

  it("is false when no pair matches", () => {
    expect(handlesCompatible(["Trigger"], ["Message"])).toBe(false);
  });
});
