{
 "title": "Supavisor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(supavisor_prom_ex_prom_ex_status_info, region)"
    }
   },
   {
    "name": "nodehost",
    "label": "Node",
    "query": {
     "query": "label_values(supavisor_prom_ex_prom_ex_status_info, host)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(supavisor_connections_active, tenant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MMM Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max over 7d sum active clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(sum(supavisor_connections_active{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}))[7d])"
    }
   ]
  },
  {
   "title": "Max over 7d queries per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(sum(rate(supavisor_client_queries_count{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"})))[7d])"
    }
   ]
  },
  {
   "title": "Max concurrent tenants ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(sum(supavisor_tenants_active{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}))[7d])"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "supavisor_prom_ex_osmon_ram_usage{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "supavisor_prom_ex_osmon_cpu_util{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "BEAM Run Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_run_queue_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "per Tenant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(supavisor_client_network_send{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"})) by (region)",
     "legendFormat": "send {{region}}"
    },
    {
     "expr": "-sum(increase(supavisor_client_network_recv{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"})) by (region)",
     "legendFormat": "recv {{region}}"
    }
   ]
  },
  {
   "title": "Downstream Mbps - TEST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(supavisor_client_network_send{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}) * 8) by (region)",
     "legendFormat": "send {{region}}"
    },
    {
     "expr": "-sum(rate(supavisor_client_network_recv{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}) * 8) by (region)",
     "legendFormat": "recv {{region}}"
    }
   ]
  },
  {
   "title": "The total count of active clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(supavisor_connections_active{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}) by (region)",
     "legendFormat": "{{$region}}"
    }
   ]
  },
  {
   "title": "Upstream network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(supavisor_db_network_send{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"})) by (region)",
     "legendFormat": "send {{region}}"
    },
    {
     "expr": "-sum(increase(supavisor_db_network_recv{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"})) by (region)",
     "legendFormat": "recv {{region}}"
    }
   ]
  },
  {
   "title": "Client query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(supavisor_client_query_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "The total count of active tenants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(supavisor_tenants_active{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Pool checkout duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(supavisor_pool_checkout_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(supavisor_client_queries_count{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (region)",
     "legendFormat": "{{$region}}"
    }
   ]
  },
  {
   "title": "Client connection duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(supavisor_client_connection_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Client query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(supavisor_client_query_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(supavisor_client_query_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(supavisor_client_query_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(supavisor_client_query_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(supavisor_client_queries_count{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (region)",
     "legendFormat": "{{$region}}"
    }
   ]
  },
  {
   "title": "Pool checkout duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(supavisor_pool_checkout_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(supavisor_pool_checkout_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(supavisor_pool_checkout_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(supavisor_pool_checkout_duration_bucket{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (le))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Successful joins per second",
   "type": "timeseries",
   "description": "The total number of successful joins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(supavisor_client_joins_ok{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Attempted DbHandlers per second",
   "type": "timeseries",
   "description": "The total number of database connections by db_handler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(supavisor_db_handler_db_connection_count{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Created DbHandlers per second",
   "type": "timeseries",
   "description": "The total number of created db_handler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(supavisor_db_handler_started_count{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Failed joins per second",
   "type": "timeseries",
   "description": "The total number of failed joins",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(supavisor_client_joins_fail{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Stopped DbHandlers per second",
   "type": "timeseries",
   "description": "The total number of stopped db_handler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum(rate(supavisor_db_handler_stopped_count{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Beam",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_uptime_milliseconds_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "Port Count",
   "type": "stat",
   "description": "The number of currently active ports.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_port_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "stat",
   "description": "The number of running BEAM processes currently running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_process_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "ETS Table Count",
   "type": "stat",
   "description": "The number of currently allocated ETS tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_ets_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "Run Queue - Normal",
   "type": "stat",
   "description": "Normal run queue length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_run_queue_count{region=~\"$region\", host=~\"$nodehost\", type=\"normal\"}",
     "legendFormat": "{{region}} / {{host}}"
    }
   ]
  },
  {
   "title": "Atom Count",
   "type": "stat",
   "description": "The number of atoms currently in the atom table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_atom_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "{{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "BEAM Allocated Memory",
   "type": "timeseries",
   "description": "Stats on the current memory usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_memory_allocated_bytes{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Total - {{region}}/{{host}}"
    },
    {
     "expr": "supavisor_prom_ex_beam_memory_atom_total_bytes{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Atoms - {{region}}/{{host}}"
    },
    {
     "expr": "supavisor_prom_ex_beam_memory_binary_total_bytes{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Binaries - {{region}}/{{host}}"
    },
    {
     "expr": "supavisor_prom_ex_beam_memory_code_total_bytes{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Code - {{region}}/{{host}}"
    },
    {
     "expr": "supavisor_prom_ex_beam_memory_ets_total_bytes{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "ETS - {{region}}/{{host}}"
    },
    {
     "expr": "supavisor_prom_ex_beam_memory_processes_total_bytes{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Processes - {{region}}/{{host}}"
    },
    {
     "expr": "supavisor_prom_ex_beam_memory_persistent_term_total_bytes{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Persistent Term - {{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "BEAM Run Queue",
   "type": "timeseries",
   "description": "Stats on the current memory usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_run_queue_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Total - {{region}}/{{host}}"
    }
   ]
  },
  {
   "title": "ETS Tables",
   "type": "timeseries",
   "description": "The number of active ETS tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "supavisor_prom_ex_beam_stats_ets_count{region=~\"$region\", host=~\"$nodehost\"}",
     "legendFormat": "Active ETS Tables - {{region}}/{{nodehost}}"
    }
   ]
  }
 ]
}